run: # Configurations for a specific run
  random_seed: 1234 # Integer number of specifying random seed
  log_dir: demo_all # String for indicating where to save all the information, including models and computed signals. We can reuse the models saved in the same log_dir.

audit: # the configurations for the MIA
  privacy_game: privacy_loss_sample #privacy_loss_model #avg_privacy_loss_training_algo # the configuarations for the privacy loss game
  device: cuda:1 # indicate on which device we conduct the MIA
  audit_batch_size: 1000 # the batch size for computing signals for inferring membership information
  split_method: uniform # spliting methods among reference datasets
  report_log: report_sample # String that indicates the folder where we save the and auditing report.
  key: data_idx # String for indicating the meaning of the idx. We support data_idx, model_idx or none.
  idx: 1 # Integer number indicating the data index for which we want to show the performance difference

train: # Configuration for training
  type: pytorch # Training framework (we only support pytorch now).
  epochs: 30 # Integer number for indicating the epochs for training target model.
  batch_size: 64 # Integer number for indicating batch size for training the target model.
  test_batch_size: 10000 # Integer number for indicating batch size for evaluating the target model.
  optimizer: Adam # String which indicates the optimizer. We support Adam and SGD.
  lr: 0.001 # Float number for indicating learning rate for training the target model.
  wd: 0 # Float number for indicating weight decay for training the target model.
  model_name: CNN # String for indicating the model type. We support CNN. More model types can be added in model.py.
  device: cuda:0 # String for indicating the device we want to use for training models.
  key: data_idx # String for indicating the meaning of the idx. We support data_idx, model_idx or none.
  idx: 1 # Integer number for indicating the model index or data index.
  num_in_models: 40 # Integer number that indicates how many target models trained on idx
  num_out_models: 40 # Integer number that indicates how many target models not trained on idx

data: # Configuration for data
  dataset: cifar10 # String indicates the name of the dataset
  f_train: 0.3 # Float number from 0 to 1 indicating the fraction of the train dataset
  f_test: 0.3 # Float number from 0 to 1 indicating the fraction of the test dataset
  split_method: uniform # String for indicating the methods of splitting the dataset between train, test, and auditing.
  f_audit: 0.3 # Float from 0 to 1, indicating the fraction of the auditing dataset
