run: # Configurations for a specific run
  random_seed: 12345 # Integer number of specifying random seed 
  log_dir: temp_test # String for indicating where to save all the information, including models and computed signals. We can reuse the models saved in the same log_dir.

audit: # Configurations for auditing
  privacy_game: privacy_loss_model # Indicate the privacy game from privacy_loss_model, avg_privacy_loss_training_algo, privacy_loss_sample
  device: cpu # String for indicating on which device we conduct the membership inference attack and train reference models.
  audit_batch_size: 1000 # Integer number for indicating the batch size for computing signals in the privacy meter.
  algorithm: reference # String for indicating the membership inference attack. We currently support population, reference.
  report_log: report_reference # String that indicates the folder where we save the and auditing report.
  num_reference_models: 10 # Integer number for indicating how many reference models we need to train for auditing, if the reference attack is used.
  batch_size: 16 # Integer number for indicating the batch size of training the reference models if reference attack is used.
  f_reference_dataset: 1 # Float number for indicating the ratio between the reference train dataset and the target train dataset.
  optimizer: Adam # String which indicates the optimizer for training reference models. We support Adam and SGD.
  lr: 0.001 # Float number for indicating learning rate for training the reference model.
  wd: 0 # Float number for indicating weight decay for training the reference model.
  model_name: CNN # String for indicating the model type. We support CNN,alexnet. More model type can be added in model.py.
  epochs: 30 # Integer number for indicating the epochs for training target model.
  split_method: uniform # String for indicating the splitting methods for reference dataset. We support uniform and leave_one_out.
  key: none # String for indicating the meaning of the idx. We support data_idx and none for reusing existing reference models. data_idx search for models which include or exclude the data point indicated using idx. Otherwise, the reference models are the ones that have the same training setting as indicated above.
  idx: none # Integer number for the model index or data index.
 
train: # Configuration for training
  type: pytorch # Training framework (we only support pytorch now).
  epochs: 30 # Integer number for indicating the epochs for training target model.
  batch_size: 16 # Integer number for indicating batch size for training the target model.
  test_batch_size: 10000 # Integer number for indicating batch size for evaluating the target model.
  optimizer: Adam # String which indicates the optimizer. We support Adam and SGD.
  lr: 0.001 # Float number for indicating learning rate for training the target model.
  wd: 0 # Float number for indicating weight decay for training the target model.
  model_name: CNN # String for indicating the model type. We support CNN. More model types can be added in model.py.
  device: cpu # String for indicating the device we want to use for training models.
  key: none # String for indicating the meaning of the idx. We support data_idx, model_idx or none.
  num_target_model: 1 #Integer number for indicating how many target models we want to audit for the privacy game
  
data:  # Configuration for data
  dataset: cifar10 # String indicates the name of the dataset 
  f_train: 0.041666666666666664 # Float number from 0 to 1 indicating the fraction of the train dataset
  f_test: 0.041666666666666664 # Float number from 0 to 1 indicating the fraction of the test dataset
  split_method: no_overlapping # String for indicating the methods of splitting the dataset between train, test, and auditing. Note that, compare to the baseline, we don't use the class balanced splitting.
  f_audit: 0.06666666666666667 # Float from 0 to 1, indicating the fraction of the auditing dataset



## Expected time:
# 2023-01-17 17:47:53 INFO     Prepare the datasets costs 39.841452836990356 seconds
# 2023-01-17 17:48:11 INFO     Prepare 0-th target model costs 18.17739987373352 seconds: Train accuracy 0.9116, Train Loss 0.29939286012178773; Test accuracy 0.4188, Test Loss 2.706223726272583
# 2023-01-17 17:48:11 INFO     Prepare the target model costs 18.1793429851532 seconds
# 2023-01-17 17:48:29 INFO     Prepare 0-th reference model costs 17.654411554336548 seconds: Train accuracy (on auditing dataset) 0.4212, Train Loss 2.713433693928324
# 2023-01-17 17:48:47 INFO     Prepare 1-th reference model costs 17.9170982837677 seconds: Train accuracy (on auditing dataset) 0.4196, Train Loss 2.7727788720920588
# 2023-01-17 17:49:05 INFO     Prepare 2-th reference model costs 17.799418687820435 seconds: Train accuracy (on auditing dataset) 0.4244, Train Loss 2.7798079100384077
# 2023-01-17 17:49:23 INFO     Prepare 3-th reference model costs 17.68532133102417 seconds: Train accuracy (on auditing dataset) 0.4296, Train Loss 2.7501431323920085
# 2023-01-17 17:49:40 INFO     Prepare 4-th reference model costs 17.40951156616211 seconds: Train accuracy (on auditing dataset) 0.4176, Train Loss 2.782392448680416
# 2023-01-17 17:49:58 INFO     Prepare 5-th reference model costs 17.857390642166138 seconds: Train accuracy (on auditing dataset) 0.4292, Train Loss 2.711431478239169
# 2023-01-17 17:50:16 INFO     Prepare 6-th reference model costs 17.783441066741943 seconds: Train accuracy (on auditing dataset) 0.4216, Train Loss 2.726758022976529
# 2023-01-17 17:50:33 INFO     Prepare 7-th reference model costs 17.832836627960205 seconds: Train accuracy (on auditing dataset) 0.4292, Train Loss 2.7159559962096487
# 2023-01-17 17:50:51 INFO     Prepare 8-th reference model costs 17.528289318084717 seconds: Train accuracy (on auditing dataset) 0.4336, Train Loss 2.6994144635595334
# 2023-01-17 17:51:09 INFO     Prepare 9-th reference model costs 17.753455877304077 seconds: Train accuracy (on auditing dataset) 0.4304, Train Loss 2.7628811658567685
# 2023-01-17 17:51:09 INFO     Prepare the information source costs 177.36975574493408 seconds
# 2023-01-17 17:51:10 INFO     Prepare privacy meter results costs 0.8038098812103271 seconds
# 2023-01-17 17:51:13 INFO     Prepare the plot for the privacy risk report costs 2.951735734939575 seconds
# 2023-01-17 17:51:13 INFO     Run the priavcy meter for the all steps costs 239.1467845439911 seconds

## Expected outcome:
# AUC: 0.773