run: # the configurations for the running setup
  random_seed: 1234 

attack: # the configurations for the MIA
  attack_algorithm: reference_attack
  num_reference_models: 10
  privacy_game: privacy_loss_model # the configuarations for the privacy loss game


train: # the configuarations for the training
  type: pytorch
  epochs: 20
  train_batch_size: 64
  test_batch_size: 10000
  optimizer: Adam
  lr: 0.001
  wd: 0
  # momentum: 0.05
  model: CNN
  device: cuda:0

data:  # the configuarations for the dataset
  dataset: cifar10
  f_train: 0.8
  f_test: 0.1
  f_audit: 0.1
  num_split: 1 # repeat the split f_split times
