run: # Configurations for a specific run
  random_seed: 12345 # Integer number of specifying random seed
  log_dir: demo_lira_attack # String for indicating where to save all the information, including models and computed signals. We can reuse the models saved in the same log_dir.
  time_log: True # Indicate whether to log the time for each step

audit: # Configurations for auditing
  privacy_game: privacy_loss_model # Indicate the privacy game from privacy_loss_model, avg_privacy_loss_training_algo, privacy_loss_sample
  algorithm: reference_in_out # String for indicating the membership inference attack. We currently support population, reference.
  report_log: report_in_out_rescaled_logits # String that indicates the folder where we save the and auditing report.
  signal: rescaled_logits # String for indicating the attack signal. We support loss, rescaled_logits.
  device: cuda:0 # String for indicating on which device we conduct the membership inference attack and train reference models.
  audit_batch_size: 1000 # Integer number for indicating the batch size for computing signals in the privacy meter.
  num_in_models: 8 # Integer number that indicates how many target models trained on idx
  num_out_models: 8 # Integer number that indicates how many target models not trained on idx
  augmentation: None # Indicate whether to use augmentation for the query points
  batch_size: speedyresnet_batch_size # Integer number for indicating the batch size of training the reference models if reference attack is used.
  optimizer: speedyresnet_optimizer # String which indicates the optimizer for training reference models. We support Adam and SGD.
  learning_rate: speedyresnet_learning_rate # Float number for indicating learning rate for training the reference model.
  weight_decay: speedyresnet_weight_decay # Float number for indicating weight decay for training the reference model.
  model_name: speedyresnet # String for indicating the model type. We support CNN, wrn28-1, wrn28-2, wrn28-10, vgg16, nn and speedyresnet (requires cuda). More model types can be added in model.py.
  epochs: speedyresnet_epochs # Integer number for indicating the epochs for training target model.
  test_batch_size: 250 # Integer number for indicating batch size for evaluating the target model.
  num_test_size: 1000 # Integer number for indicating the size of the test dataset for evaluating the target model during the training. This should be divisible by test_batch_size.
  fix_variance: True # Indicate hwether to fix the variance of the signals for all data points

train: # Configuration for training
  type: pytorch # Training framework (we only support pytorch now).
  model_name: speedyresnet # String for indicating the model type. We support CNN. More model types can be added in model.py.
  device: cuda:0 # String for indicating the device we want to use for training models.
  num_in_models: 8 # Integer number that indicates how many target models trained on idx
  num_out_models: 8 # Integer number that indicates how many target models not trained on idx
  num_target_model: 1 # Number of total models we want to test
  optimizer: speedyresnet_optimizer
  learning_rate: speedyresnet_learning_rate
  weight_decay: speedyresnet_weight_decay
  batch_size: speedyresnet_batch_size
  epochs: speedyresnet_epochs
  test_batch_size: 5000 # Integer number for indicating batch size for evaluating the target model.

data: # Configuration for data
  dataset: cifar10 # String indicates the name of the dataset
  data_dir: ../data
  keep_ratio: 0.5 # the ratio of keeping the point for the training dataset.
  dataset_size: 50000 # the size of the whole dataset used.
